Friends!
anysphere/client pull request #37
Opened 2022-06-24 20:05 UTC by arvid220u

"
Update anysphere/asphr commit SHA
🔗 https://github.com/anysphere/asphr/commit/6dbadec9e3796489496ea6406cfd07cd012bb9ba

2022-06-28 01:09 UTC, arvid220u commented on daemon/rpc/daemon_rpc.cc
> +        getIncomingAsyncFriendRequestsResponse) {
We want to check that the user is registered before doing this

2022-06-28 01:10 UTC, arvid220u commented on daemon/rpc/daemon_rpc.cc
> +  // clone of the above
want to ASPHR_LOG here that we're in this rpc call

2022-06-28 01:10 UTC, arvid220u commented on daemon/rpc/daemon_rpc.cc
> +        decideAsyncFriendRequestResponse) {
check if registered, ASPHR_LOG

2022-06-30 05:36 UTC, sualehasif requested changes
some initial thoughts.

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/constants.hpp
>  #include "sodium.h"
do we want to call these cryptography contstants

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/constants.hpp
> +constexpr int ENCRYPTED_ACKING_BYTES =
I.e. should we separate crypto constants from others.

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/crypto.cc
>    unsigned char public_key[crypto_kx_PUBLICKEYBYTES];
should we convert these to spans? (as by the GSL?)

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/crypto.cc
>    unsigned char public_key[crypto_kx_PUBLICKEYBYTES];
nvm, we cant??

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/crypto.cc
> +      string(reinterpret_cast<char*>(secret_key), crypto_box_SECRETKEYBYTES)};
formatting errors here

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/crypto.cc
> +auto generate_user_id(const string& username, int allocation,
feels like this should take in a struct. Or something that prevents argument rearrangement??

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/crypto.cc
> +  return username + "@" + std::to_string(allocation) + "@" + kx_public_key_b64 +
I think this might be a bit sketchy. @arvid220u 
Can I propose using “-“ or “_”

I think “@“ can be seriously misinterpreted

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/crypto.cc
> +  if (sodium_base642bin(reinterpret_cast<unsigned char*>(kx_public_key.data()),
ah, since we have no typechecking whatsoever on these. Do you think it would be wise to copy paste their docs here?

2022-06-30 05:36 UTC, sualehasif commented on daemon/crypto/crypto_test.cc
> +
mmm, please, can we comment the partitions that we are checking here.

2022-06-30 05:36 UTC, sualehasif commented on daemon/db/tests.rs
worth writing partitions here too for our future memory.

2022-06-30 05:52 UTC, Tom-CCS commented on daemon/crypto/crypto.cc
> +  return username + "@" + std::to_string(allocation) + "@" + kx_public_key_b64 +
This method is no longer used.

2022-06-30 23:36 UTC, arvid220u reviewed
lgtm

2022-06-30 23:37 UTC, sualehasif approved these changes
lgtm gg

2022-06-30 23:37 UTC, arvid220u commented on daemon/identifier/base58.cc
> +  // Skip leading zeroes in base58 result.
yes !

2022-06-30 23:46 UTC, merged